#                            Exercise 12

### Exercise 01 : 

In [51]:
import numpy as np

arr = np.random.randint(1000 , size=(4,5,3))
print('the dimensions of created array : ' , arr.ndim)
print('the shape of created array : ' , arr.shape )

the dimensions of created array :  3
the shape of created array :  (4, 5, 3)


In [52]:
arr

array([[[746, 453, 733],
        [554, 551, 989],
        [682, 879, 293],
        [ 31, 956, 999],
        [880, 741, 534]],

       [[577, 616, 542],
        [400, 931, 694],
        [382, 677, 873],
        [886, 289, 801],
        [570, 917, 863]],

       [[882, 535,  36],
        [400, 677, 431],
        [711, 704, 273],
        [124,  10, 119],
        [286, 782, 167]],

       [[  2, 241, 236],
        [ 40, 712,  30],
        [754, 496, 696],
        [900, 471, 819],
        [ 91, 663, 622]]])

### Exercise 02 : 

In [53]:
arr2 = np.reshape(arr, (20,3))
arr2

array([[746, 453, 733],
       [554, 551, 989],
       [682, 879, 293],
       [ 31, 956, 999],
       [880, 741, 534],
       [577, 616, 542],
       [400, 931, 694],
       [382, 677, 873],
       [886, 289, 801],
       [570, 917, 863],
       [882, 535,  36],
       [400, 677, 431],
       [711, 704, 273],
       [124,  10, 119],
       [286, 782, 167],
       [  2, 241, 236],
       [ 40, 712,  30],
       [754, 496, 696],
       [900, 471, 819],
       [ 91, 663, 622]])

In [54]:
print('dimension of new array is : ' , arr2.ndim) 

dimension of new array is :  2


In [55]:
print('shape of new array is : ' , arr2.shape)

shape of new array is :  (20, 3)


### Exercise 03 : 

In [56]:
arr = np.array([
                [10, 20, 30, 40], 
                [50, 60, 70, 80]
                ])
 
result = np.where(arr == 50)
print(" Tuple of index value of 50 is : ", result)

 Tuple of index value of 50 is :  (array([1], dtype=int64), array([0], dtype=int64))


In [57]:
# zip the 2 arrays to get the exact coordinates
listOfCoordinates= list(zip(result[0], result[1]))

# iterate over the list of coordinates
for cord in listOfCoordinates:
    print(" index value of 50 is : ", cord)    
    

 index value of 50 is :  (1, 0)


### Exercise 04 : 

In [70]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print('element type of array is : ' , arr.dtype)
print('element type of array is : ' , type(arr))

element type of array is :  int32
element type of array is :  <class 'numpy.ndarray'>


In [59]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]], dtype = float)
print(arr.dtype)

float64


### Exercise 05 : 

In [73]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [78]:
print(arr1)

[1 2 3]


In [75]:
arr2

array([4, 5, 6])

In [76]:
arr_new = np.concatenate((arr1, arr2))
arr_new 

array([1, 2, 3, 4, 5, 6])

In [77]:
print('element type of array is : ' , type(arr_new))

element type of array is :  <class 'numpy.ndarray'>
