<div style="text-align: center"> <h1>Exercises 12</h1></div>
<div style="text-align: center; color: red;"> <h2>Numpy</h2></div>

<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 01</h2></div>

<div style="color:darkblue;"> <h3>Create an 3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.</h3></div>

In [57]:
import numpy as np

In [58]:
arr = np.array([
                [
                    [1, 2, 3],
                    [20, 30, 10],
                    [3, 4, 5],
                    [4, 5, 8],
                    [4, 5, 7]
                ],
                [
                     [1, 2, 3],
                    [20, 30, 10],
                    [3, 4, 5],
                    [4, 5, 8],
                    [4, 5, 7]
                ],
                [
                     [1, 2, 3],
                    [20, 30, 10],
                    [3, 4, 5],
                    [4, 5, 8],
                    [4, 5, 7]
                ],
                [
                    [1, 2, 3],
                    [20, 30, 10],
                    [3, 4, 5],
                    [4, 5, 8],
                    [4, 5, 7]
                ]
              ])

In [61]:
print(f"shape: {arr.shape}")
print(f"dimention: {arr.ndim}")

shape: (4, 5, 3)
dimention: 3


<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 02</h2></div>

<div style="color:darkblue;"> <h3>change the shape of created array in the exercise 01 to (20, 3) and check the current dimensions! </h3></div>

In [63]:
new_arr = arr.reshape(20, 3)
#print(new_arr)
print(f"shape: {new_arr.shape}")

shape: (20, 3)


<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 03</h2></div>

<div style="color:darkblue;"> <h3>index and print the number 50 from the arr.</h3></div>

### arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [64]:
arr = np.array([
        [10, 20, 30, 40],
        [50, 60, 70, 80]
    ])
arr[1,0]

50

<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 04</h2></div>

<div style="color:darkblue;"> <h3>Change the element datatype of the arr to float!</h3></div>

### arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [71]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr.astype(float)

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [72]:
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [75]:
np.float64(arr)

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [77]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]], dtype = "d")
arr

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 05</h2></div>

<div style="color:darkblue;"> <h3>join arr1 and arr2 into a single array!</h3></div>

### arr1 = np.array([1, 2, 3])
### arr2 = np.array([4, 5, 6])

In [90]:
arr1 = np.array([1, 2, 3,4])
arr2 = np.array([4, 5, 6, 7])

In [89]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [92]:
arr3 = np.stack((arr1, arr2))
print(arr3)

[[1 2 3 4]
 [4 5 6 7]]


In [96]:
arr3 = np.hstack((arr1, arr2)) #row
print(arr3)

[1 2 3 4 4 5 6 7]


In [97]:
arr3 = np.vstack((arr1, arr2)) #column
print(arr3)

[[1 2 3 4]
 [4 5 6 7]]


In [98]:
arr3 = np.dstack((arr1, arr2)) #depth
print(arr3)

[[[1 4]
  [2 5]
  [3 6]
  [4 7]]]
